logging:
  format: console
  level: debug
  name: mock-tinder
  outputs:
    - stdout
  error_outputs:
    - stderr

auth:
  secret_key: THIS_MUST_BE_CHANGED_IN_PRODUCTION
  expires_time: 86400

gin_mode: debug

server:
  host: 0.0.0.0
  port: 8080

database:
  log_level: debug
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres